/* ====================================
   reasons.js — 101 Universal Reasons (RU + UZ)
   ==================================== */

/* --- RUSSIAN --- */
window.REASONS_RU = [
    'Потому что ты излучаешь свет, {name}! ✨',
    'Потому что твоя улыбка освещает любую комнату',
    'Потому что ты никогда не сдаёшься',
    'Потому что ты видишь красоту в мелочах',
    'Потому что ты делаешь мир добрее',
    'Потому что ты сильнее, чем думаешь',
    'Потому что ты вдохновляешь окружающих',
    'Потому что твой смех заразителен',
    'Потому что ты умеешь найти выход из любой ситуации',
    'Потому что ты — настоящая волшебница',
    'Потому что ты ценишь каждое мгновение',
    'Потому что рядом с тобой всегда тепло',
    'Потому что ты умеешь слушать',
    'Потому что ты отважная и решительная',
    'Потому что ты создаёшь уют, {name}',
    'Потому что ты веришь в людей',
    'Потому что ты — пример для подражания',
    'Потому что ты умеешь прощать',
    'Потому что ты любишь животных',
    'Потому что ты находишь добро в каждом',
    'Потому что ты умеешь мечтать',
    'Потому что ты заботливая и внимательная',
    'Потому что ты — лучик солнца в пасмурный день',
    'Потому что ты ценишь дружбу',
    'Потому что ты умеешь радоваться за других',
    'Потому что ты талантлива',
    'Потому что ты не боишься быть собой',
    'Потому что ты умеешь удивлять',
    'Потому что ты делаешь обычные моменты особенными',
    'Потому что ты — чудо, {name}!',
    'Потому что ты всегда находишь нужные слова',
    'Потому что ты стремишься к лучшему',
    'Потому что ты хранишь тёплые воспоминания',
    'Потому что ты умеешь сопереживать',
    'Потому что ты ценишь каждого человека',
    'Потому что ты излучаешь позитив',
    'Потому что ты идёшь вперёд, несмотря ни на что',
    'Потому что ты веришь в чудеса',
    'Потому что ты — олицетворение доброты',
    'Потому что ты умеешь радоваться мелочам',
    'Потому что ты щедрая душой',
    'Потому что с тобой невозможно скучать',
    'Потому что ты умеешь поддержать словом',
    'Потому что ты сияешь изнутри',
    'Потому что ты — воплощение грации, {name}',
    'Потому что ты умеешь ценить тишину',
    'Потому что ты открыта новому',
    'Потому что ты неповторима',
    'Потому что ты наполняешь мир красками',
    'Потому что ты всегда остаёшься честной',
    'Потому что ты умеешь смеяться над собой',
    'Потому что ты любишь учиться',
    'Потому что ты заряжаешь энергией',
    'Потому что ты — настоящий друг',
    'Потому что ты умеешь создавать праздник',
    'Потому что ты ценишь природу',
    'Потому что ты не следуешь толпе',
    'Потому что ты мудрая не по годам',
    'Потому что ты делаешь добро без ожиданий',
    'Потому что ты — яркая звезда, {name}! ⭐',
    'Потому что ты умеешь быть благодарной',
    'Потому что ты несёшь гармонию',
    'Потому что ты веришь в силу добра',
    'Потому что ты — источник вдохновения',
    'Потому что ты принимаешь людей такими, какие они есть',
    'Потому что ты умеешь терпеливо ждать',
    'Потому что ты заслуживаешь всего самого лучшего',
    'Потому что ты ставишь цели и достигаешь их',
    'Потому что ты генерируешь тепло вокруг себя',
    'Потому что ты — живое доказательство, что ангелы существуют',
    'Потому что ты умеешь хранить секреты',
    'Потому что ты разбираешься в людях',
    'Потому что ты всегда поддерживаешь близких',
    'Потому что ты — воплощение нежности',
    'Потому что ты ценишь искусство',
    'Потому что ты умеешь находить компромиссы',
    'Потому что ты — лучшая версия себя каждый день',
    'Потому что ты любишь жизнь, {name}',
    'Потому что ты не боишься перемен',
    'Потому что ты помогаешь другим расти',
    'Потому что ты создаёшь вокруг себя атмосферу любви',
    'Потому что ты умеешь видеть возможности там, где другие видят проблемы',
    'Потому что ты — невероятно сильная',
    'Потому что ты умеешь расставлять приоритеты',
    'Потому что ты хранишь традиции',
    'Потому что ты — образец элегантности',
    'Потому что ты никогда не перестаёшь учиться',
    'Потому что ты ценишь каждый закат',
    'Потому что ты даришь радость окружающим',
    'Потому что ты — королева, {name}! 👑',
    'Потому что ты умеешь быть счастливой',
    'Потому что каждый день с тобой — подарок',
    'Потому что ты — воплощение красоты и силы',
    'Потому что ты дарим миру надежду',
    'Потому что ты любишь без условий',
    'Потому что ты веришь в лучшее будущее',
    'Потому что ты — просто невероятная',
    'Потому что ты создаёшь историю каждый день',
    'Потому что ты — драгоценность этого мира',
    'Потому что ты помнишь всех, кто тебе дорог',
    'Потому что ты — самое прекрасное, что есть, {name}! 💖'
];

/* --- UZBEK --- */
window.REASONS_UZ = [
    'Chunki sen nur sochasan, {name}! ✨',
    'Chunki sening tabassumdan har bir xona yorishadi',
    'Chunki sen hech qachon taslim bo\'lmaysan',
    'Chunki sen kichik narsalarda go\'zallik ko\'rasan',
    'Chunki sen dunyoni mehribon qilasan',
    'Chunki sen o\'zingdan kuchliroqsan',
    'Chunki sen atrofingdagilarni ilhomlantirasan',
    'Chunki sening kuling yuqumli',
    'Chunki sen har qanday vaziyatdan chiqish yo\'lini topasan',
    'Chunki sen — haqiqiy sehrgar',
    'Chunki sen har bir lahzani qadrleysan',
    'Chunki sen yonida bo\'lganda doimo iliq',
    'Chunki sen tinglashni bilasan',
    'Chunki sen jasur va qat\'iyatli',
    'Chunki sen qulaylik yaratasan, {name}',
    'Chunki sen odamlarga ishonasan',
    'Chunki sen — ibrat qilsa bo\'ladigan inson',
    'Chunki sen kechira olasan',
    'Chunki sen hayvonlarni yaxshi ko\'rasan',
    'Chunki sen hamma odamda yaxshilik topasan',
    'Chunki sen orzu qilishni bilasan',
    'Chunki sen g\'amxo\'r va e\'tiborlisan',
    'Chunki sen — bulutli kunda quyosh nuriga o\'xshaysan',
    'Chunki sen do\'stlikni qadrleysan',
    'Chunki sen boshqalar uchun ham xursand bo\'la olasan',
    'Chunki sen iste\'dodlisan',
    'Chunki sen o\'zing bo\'lishdan qo\'rqmaysan',
    'Chunki sen hayratga solishni bilasan',
    'Chunki sen oddiy lahzalarni maxsus qilasan',
    'Chunki sen — mo\'jiza, {name}!',
    'Chunki sen doimo kerakli so\'zlarni topasan',
    'Chunki sen yaxshiroqqa intilasan',
    'Chunki sen iliq xotiralarni saqlaysan',
    'Chunki sen hamdardlik qila olasan',
    'Chunki har bir insonni qadrleysan',
    'Chunki sen ijobiy energiya tarqatasan',
    'Chunki sen hech narsadan qat\'iy nazar oldinga borasan',
    'Chunki sen mo\'jizalarga ishonasan',
    'Chunki sen — mehribonlikning timsoli',
    'Chunki sen kichik narsalarga ham xursand bo\'lasan',
    'Chunki sen ochiq ko\'ngilli',
    'Chunki sen bilan zerikarli bo\'lmaydi',
    'Chunki sen so\'z bilan qo\'llab-quvvatlashni bilasan',
    'Chunki sen ichdan nurlanasan',
    'Chunki sen — nafosatning timsoli, {name}',
    'Chunki sen sukunatni qadrleysan',
    'Chunki sen yangiliklarni qabul qilasan',
    'Chunki sen takrorlanmas',
    'Chunki sen dunyoni ranglar bilan to\'ldirasan',
    'Chunki sen doimo halol qolasan',
    'Chunki sen o\'zingga kulishni bilasan',
    'Chunki sen o\'rganishni yaxshi ko\'rasan',
    'Chunki sen energiya berasan',
    'Chunki sen — haqiqiy do\'st',
    'Chunki sen bayram yaratishni bilasan',
    'Chunki sen tabiatni qadrleysan',
    'Chunki sen olomonga ergashib ketmaysan',
    'Chunki sen yoshiga nisbatan dono',
    'Chunki sen hech narsa kutmasdan yaxshilik qilasan',
    'Chunki sen — yorqin yulduz, {name}! ⭐',
    'Chunki sen minnatdor bo\'lishni bilasan',
    'Chunki sen uyg\'unlikni olib kelasan',
    'Chunki sen yaxshilik kuchiga ishonasan',
    'Chunki sen ilhom manbai',
    'Chunki sen odamlarni bor holicha qabul qilasan',
    'Chunki sen sabr bilan kutishni bilasan',
    'Chunki sen eng yaxshi narsalarga loyiqsan',
    'Chunki sen maqsad qo\'yasan va unga yetasan',
    'Chunki sen atrofingga iliqlik tarqatasan',
    'Chunki sen — farishtalar borligining isboti',
    'Chunki sen sirlarni saqlashni bilasan',
    'Chunki sen odamlarni yaxshi tushunasan',
    'Chunki sen doimo yaqinlaringni qo\'llab-quvvatlaysan',
    'Chunki sen — noziklikning timsoli',
    'Chunki sen san\'atni qadrleysan',
    'Chunki kelishuvga kelishni bilasan',
    'Chunki har kuni o\'zingning eng yaxshi versiyasin',
    'Chunki sen hayotni yaxshi ko\'rasan, {name}',
    'Chunki sen o\'zgarishlardan qo\'rqmaysan',
    'Chunki sen boshqalarga o\'sishga yordam berasan',
    'Chunki sen atrofingda sevgi muhitini yaratasan',
    'Chunki boshqalar muammo ko\'rgan joyda imkoniyat topasan',
    'Chunki sen — ajoyib darajada kuchli',
    'Chunki sen birinchi navbat nima ekanini bilasan',
    'Chunki sen an\'analarni saqlaysan',
    'Chunki sen nafosatning namunasi',
    'Chunki sen o\'rganishni hech to\'xtatmaysan',
    'Chunki har bir quyosh botishini qadrleysan',
    'Chunki atrofingdagilarga quvonch ulashasan',
    'Chunki sen — malika, {name}! 👑',
    'Chunki sen baxtli bo\'lishni bilasan',
    'Chunki sen bilan bo\'lgan har kun — sovg\'a',
    'Chunki sen — go\'zallik va kuchning timsoli',
    'Chunki sen dunyoga umid ulashasan',
    'Chunki sen shartsiz sevasan',
    'Chunki sen yaxshiroq kelajakka ishonasan',
    'Chunki sen — shunchaki ajoyib',
    'Chunki har kuni sen tarix yaratasan',
    'Chunki sen — bu dunyoning qimmatbaho gavhari',
    'Chunki azizlaringni doimo esda saqlaysan',
    'Chunki sen — eng go\'zal narsa, {name}! 💖'
];
